---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1545300/public_html/
    - /bin/cp -R aplikasi $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -R artikel $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH



