---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1545300/public_html/
    - /bin/cp -R aplikasi $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -R PortfolioRedi $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about-1.html $DEPLOYPATH
    - /bin/cp blog-classic-grid.html $DEPLOYPATH
    - /bin/cp error-404.html $DEPLOYPATH
    - /bin/cp faq-1.html $DEPLOYPATH
    - /bin/cp portfolio.html $DEPLOYPATH



