---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1545300/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R Aplikasi $DEPLOYPATH
    - /bin/cp -R Blog $DEPLOYPATH
    - /bin/cp -R Artikel $DEPLOYPATH
    - /bin/cp -R Portfolio $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH



